–Ω–∞–∑–≤–∞–Ω–∏–µ: –î–µ–º–æ–Ω—Å—Ç—Ä–∞—Ü–∏—è –¥–µ–π—Å—Ç–≤–∏–π GitHub
run-name: ${{ github.actor }} —Ç–µ—Å—Ç–∏—Ä—É–µ—Ç –¥–µ–π—Å—Ç–≤–∏—è GitHub üöÄ
–Ω–∞: [–Ω–∞–∂–∞—Ç—å]
–≤–∞–∫–∞–Ω—Å–∏–∏:
  Explore-GitHub-Actions:
    –∑–∞–ø—É—Å–∫–∞–µ—Ç—Å—è –Ω–∞: ubuntu-latest
    —à–∞–≥–∏:
      - –≤—ã–ø–æ–ª–Ω–∏—Ç—å: echo "üéâ –ó–∞–¥–∞–Ω–∏–µ –±—ã–ª–æ –∞–≤—Ç–æ–º–∞—Ç–∏—á–µ—Å–∫–∏ –∑–∞–ø—É—â–µ–Ω–æ —Å–æ–±—ã—Ç–∏–µ–º ${{ github.event_name }}."
      - –≤—ã–ø–æ–ª–Ω–∏—Ç—å: echo "üêß –≠—Ç–æ –∑–∞–¥–∞–Ω–∏–µ —Ç–µ–ø–µ—Ä—å –≤—ã–ø–æ–ª–Ω—è–µ—Ç—Å—è –Ω–∞ —Å–µ—Ä–≤–µ—Ä–µ ${{ runner.os }}, —Ä–∞–∑–º–µ—â–µ–Ω–Ω–æ–º –Ω–∞ GitHub!"
      - –≤—ã–ø–æ–ª–Ω–∏—Ç—å: echo "üîé –ò–º—è –≤–∞—à–µ–π –≤–µ—Ç–∫–∏ ‚Äî ${{ github.ref }}, –∞ –≤–∞—à —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π ‚Äî ${{ github.repository }}."
      - –∏–º—è: –ü—Ä–æ–≤–µ—Ä–∏—Ç—å –∫–æ–¥ —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏—è
        –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–µ: actions/checkout@v5
      - –≤—ã–ø–æ–ª–Ω–∏—Ç—å: echo "üí° –†–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π ${{ github.repository }} –±—ã–ª –∫–ª–æ–Ω–∏—Ä–æ–≤–∞–Ω –≤ —Å—Ä–µ–¥—Å—Ç–≤–æ –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è."
      - –∑–∞–ø—É—Å—Ç–∏—Ç—å: echo "üñ•Ô∏è –¢–µ–ø–µ—Ä—å —Ä–∞–±–æ—á–∏–π –ø—Ä–æ—Ü–µ—Å—Å –≥–æ—Ç–æ–≤ –∫ —Ç–µ—Å—Ç–∏—Ä–æ–≤–∞–Ω–∏—é –≤–∞—à–µ–≥–æ –∫–æ–¥–∞ –Ω–∞ —É—Å—Ç—Ä–æ–π—Å—Ç–≤–µ –∑–∞–ø—É—Å–∫–∞."
      - –∏–º—è: –°–ø–∏—Å–æ–∫ —Ñ–∞–π–ª–æ–≤ –≤ —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–∏
        –≤—ã–ø–æ–ª–Ω–∏—Ç—å: |
          ls ${{ github.workspace }}
      - –≤—ã–ø–æ–ª–Ω–∏—Ç—å: echo "üçè –°—Ç–∞—Ç—É—Å —ç—Ç–æ–π —Ä–∞–±–æ—Ç—ã: ${{ job.status }}."
